spring:
  main:
    banner-mode: off
    web-application-type: none

logging:
  level:
    root: WARN
    cz.masci: INFO
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#    file: "${LOG_LEVEL_PATTERN:%5p} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

mapping:
  comparator:
    0: 
      sign: "<"
    2: 
      sign: ">"
    3: 
      sign: "<>"
      bipolar: true
    4:
      sign: "><"
      bipolar: true
  condition:
    0:
      name: "Altitude"
    2:
      name: "Airspeed"
    3:
      name: "Heading"
    4:
      name: "Pitch"
    5:
      name: "Roll"
    11:
      name: "Longitude"
    13:
      name: "Distance"
      position: true
